# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-13 21:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_goodscategorybrand_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodscategory',
            options={'verbose_name': '商品分类', 'verbose_name_plural': '商品分类'},
        ),
    ]
