# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-01 21:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_auto_20180401_2125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordergoods',
            old_name='goods_num',
            new_name='nums',
        ),
        migrations.RenameField(
            model_name='shoppingcart',
            old_name='goods_num',
            new_name='nums',
        ),
    ]
