# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-01 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0004_auto_20180401_2134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordergoods',
            old_name='nums',
            new_name='goods_num',
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='order_sn',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='订单号'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='pay_status',
            field=models.CharField(choices=[('success', '成功'), ('cancel', '取消'), ('paying', '待支付')], default='paying', max_length=10, verbose_name='订单状态'),
        ),
    ]
