# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-04 22:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0005_auto_20180401_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordergoods',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Goods', to='goods.Goods', verbose_name='商品'),
        ),
    ]
